//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExam_190840820111.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsPaperTbl
    {
        public int PaperId { get; set; }
        public string PaperName { get; set; }
        public Nullable<int> Price { get; set; }
        public string EditorName { get; set; }
        public Nullable<int> TotalNoOfReaders { get; set; }
    }
}
